import type { ProviderPreset } from '../types/provider';

/**
 * 内置供应商预设：设置页「一键添加」用
 * 覆盖市面主流标准：NewAPI / OneAPI 聚合站、OpenAI 兼容、火山引擎、可灵、MiniMax、百炼、Claude、Gemini、Ollama
 */
export const PROVIDER_PRESETS: ProviderPreset[] = [
  {
    key: 'newapi',
    label: 'NewAPI',
    protocol: 'openai',
    baseUrl: 'https://your-newapi.example.com',
    docsUrl: 'https://docs.newapi.pro/',
    description: '开源 AI 网关 / 聚合分发系统，统一 OpenAI 协议，可中转 GPT、Claude、Gemini、豆包、可灵等。',
    credentialFields: [{ key: 'apiKey', label: 'API Key', hint: '在 NewAPI 控制台「令牌」中创建' }],
    defaultModels: [
      { id: 'gpt-4o', label: 'gpt-4o（文本）', capability: 'text', mode: 'sync' },
      { id: 'gpt-image-1', label: 'gpt-image-1（图片）', capability: 'image', mode: 'sync' },
      { id: 'sora-2', label: 'sora-2（视频）', capability: 'video', mode: 'async', durations: [4, 8, 12] },
    ],
  },
  {
    key: 'oneapi',
    label: 'OneAPI',
    protocol: 'openai',
    baseUrl: 'https://your-oneapi.example.com',
    docsUrl: 'https://github.com/songquanpeng/one-api',
    description: '经典的开源 OpenAI 接口管理与分发系统，渠道管理 + 多协议转换。',
    credentialFields: [{ key: 'apiKey', label: 'API Key' }],
    defaultModels: [
      { id: 'gpt-4o', label: 'gpt-4o（文本）', capability: 'text', mode: 'sync' },
      { id: 'dall-e-3', label: 'dall-e-3（图片）', capability: 'image', mode: 'sync' },
    ],
  },
  {
    key: 'openai',
    label: 'OpenAI 官方',
    protocol: 'openai',
    baseUrl: 'https://api.openai.com',
    docsUrl: 'https://platform.openai.com/docs/api-reference',
    description: 'OpenAI 官方接口：GPT 文本、gpt-image 图片、Sora 视频。',
    credentialFields: [{ key: 'apiKey', label: 'API Key' }],
    defaultModels: [
      { id: 'gpt-4.1', label: 'gpt-4.1（文本）', capability: 'text', mode: 'sync' },
      { id: 'gpt-image-1', label: 'gpt-image-1（图片）', capability: 'image', mode: 'sync', supportsReferenceImage: true },
      { id: 'sora-2', label: 'sora-2（视频）', capability: 'video', mode: 'async', durations: [4, 8, 12] },
      {
        id: 'gpt-4o-mini-tts',
        label: 'gpt-4o-mini-tts（语音，20 语言）',
        capability: 'audio',
        mode: 'sync',
        pricing: { price: 0.012, unit: '千字符', currency: 'USD' },
      },
    ],
  },
  {
    key: 'deepseek',
    label: 'DeepSeek',
    protocol: 'openai',
    baseUrl: 'https://api.deepseek.com',
    docsUrl: 'https://api-docs.deepseek.com/',
    description: '高性价比文本模型，适合剧本、分镜、提示词扩写。',
    credentialFields: [{ key: 'apiKey', label: 'API Key' }],
    defaultModels: [
      { id: 'deepseek-chat', label: 'deepseek-chat（文本）', capability: 'text', mode: 'sync' },
      { id: 'deepseek-reasoner', label: 'deepseek-reasoner（推理）', capability: 'text', mode: 'sync' },
    ],
  },
  {
    key: 'ollama',
    label: 'Ollama 本地模型',
    protocol: 'openai',
    baseUrl: 'http://host.docker.internal:11434',
    docsUrl: 'https://github.com/ollama/ollama/blob/main/docs/openai.md',
    description: '本地跑文本模型，无需联网；Docker 部署时用 host.docker.internal 访问宿主机。',
    credentialFields: [{ key: 'apiKey', label: 'API Key（可留空）' }],
    defaultModels: [{ id: 'qwen3:8b', label: 'qwen3:8b（文本）', capability: 'text', mode: 'sync' }],
  },
  {
    key: 'siliconflow',
    label: '硅基流动 SiliconFlow',
    protocol: 'openai',
    baseUrl: 'https://api.siliconflow.cn',
    docsUrl: 'https://docs.siliconflow.cn/',
    description: '国内模型聚合平台，含文本、图片（Kolors/FLUX）、视频模型。',
    credentialFields: [{ key: 'apiKey', label: 'API Key' }],
    defaultModels: [
      { id: 'Qwen/Qwen3-32B', label: 'Qwen3-32B（文本）', capability: 'text', mode: 'sync' },
      { id: 'Kwai-Kolors/Kolors', label: 'Kolors（图片）', capability: 'image', mode: 'sync' },
      {
        id: 'FishAudio/fish-speech-1.5',
        label: 'Fish Speech 1.5（语音，多语言）',
        capability: 'audio',
        mode: 'sync',
        pricing: { price: 0.015, unit: '千字符' },
      },
    ],
  },
  {
    key: 'volcengine',
    label: '火山引擎 方舟',
    protocol: 'volcengine',
    baseUrl: 'https://ark.cn-beijing.volces.com',
    docsUrl: 'https://www.volcengine.com/docs/82379',
    description: '豆包系列：Seed 文本 / Seedream 图片 / Seedance 视频（异步任务），视频支持首尾帧。',
    credentialFields: [{ key: 'apiKey', label: 'Ark API Key', hint: '火山方舟控制台 → API Key 管理' }],
    defaultModels: [
      { id: 'doubao-seed-1-6-250615', label: '豆包 Seed 1.6（文本/多模态）', capability: 'text', mode: 'sync' },
      {
        id: 'doubao-seedream-4-0-250828',
        label: 'Seedream 4.0（图片，支持多参考图）',
        capability: 'image',
        mode: 'sync',
        supportsReferenceImage: true,
      },
      {
        id: 'doubao-seedance-1-0-pro-250528',
        label: 'Seedance 1.0 Pro（视频）',
        capability: 'video',
        mode: 'async',
        durations: [3, 5, 10],
        supportsFirstFrame: true,
        supportsLastFrame: true,
      },
      {
        id: 'doubao-seedance-1-0-lite-i2v-250428',
        label: 'Seedance 1.0 Lite 图生视频',
        capability: 'video',
        mode: 'async',
        durations: [3, 5, 10],
        supportsFirstFrame: true,
      },
      {
        id: 'doubao-seed-tts',
        label: '豆包 Seed-TTS（语音，20 语言）',
        capability: 'audio',
        mode: 'sync',
        pricing: { price: 0.35, unit: '万字符' },
      },
    ],
  },
  {
    key: 'kling',
    label: '快手可灵 Kling',
    protocol: 'kling',
    baseUrl: 'https://api-beijing.klingai.com',
    docsUrl: 'https://app.klingai.com/cn/dev/document-api',
    description: '可灵视频（AK/SK 签名，异步任务）：文生视频 / 图生视频 / 首尾帧，另含可图图片模型。',
    credentialFields: [
      { key: 'accessKey', label: 'AccessKey', hint: '可灵开放平台 AK' },
      { key: 'secretKey', label: 'SecretKey', hint: '可灵开放平台 SK' },
    ],
    defaultModels: [
      {
        id: 'kling-v2-1-master',
        label: '可灵 2.1 大师版（视频）',
        capability: 'video',
        mode: 'async',
        durations: [5, 10],
        supportsFirstFrame: true,
        supportsLastFrame: true,
      },
      {
        id: 'kling-v1-6',
        label: '可灵 1.6（视频）',
        capability: 'video',
        mode: 'async',
        durations: [5, 10],
        supportsFirstFrame: true,
        supportsLastFrame: true,
      },
      { id: 'kling-v2', label: '可图 2.0（图片）', capability: 'image', mode: 'sync', supportsReferenceImage: true },
    ],
  },
  {
    key: 'minimax',
    label: 'MiniMax 海螺',
    protocol: 'minimax',
    baseUrl: 'https://api.minimax.chat',
    docsUrl: 'https://platform.minimaxi.com/document',
    description: '海螺视频（异步）、image-01 图片、MiniMax 文本模型；部分接口需 GroupId。',
    credentialFields: [
      { key: 'apiKey', label: 'API Key' },
      { key: 'groupId', label: 'GroupId（可选）' },
    ],
    defaultModels: [
      { id: 'MiniMax-Text-01', label: 'MiniMax-Text-01（文本）', capability: 'text', mode: 'sync' },
      { id: 'image-01', label: 'image-01（图片）', capability: 'image', mode: 'sync' },
      {
        id: 'MiniMax-Hailuo-02',
        label: '海螺 02（视频）',
        capability: 'video',
        mode: 'async',
        durations: [6, 10],
        supportsFirstFrame: true,
        supportsLastFrame: true,
      },
      {
        id: 'speech-02-hd',
        label: 'speech-02-hd（语音，20 语言）',
        capability: 'audio',
        mode: 'sync',
        pricing: { price: 0.7, unit: '万字符' },
      },
    ],
  },
  {
    key: 'dashscope',
    label: '阿里云百炼 DashScope',
    protocol: 'dashscope',
    baseUrl: 'https://dashscope.aliyuncs.com',
    docsUrl: 'https://help.aliyun.com/zh/model-studio/',
    description: '通义千问文本、万相图片与视频（异步任务）',
    credentialFields: [{ key: 'apiKey', label: 'DashScope API Key' }],
    defaultModels: [
      { id: 'qwen-max', label: 'qwen-max（文本）', capability: 'text', mode: 'sync' },
      { id: 'wanx2.1-t2i-turbo', label: '万相 2.1 Turbo（图片）', capability: 'image', mode: 'async' },
      {
        id: 'wan2.2-t2v-plus',
        label: '万相 2.2 文生视频',
        capability: 'video',
        mode: 'async',
        durations: [5, 10],
        supportsFirstFrame: true,
      },
      {
        id: 'cosyvoice-v2',
        label: 'CosyVoice 2.0（语音，20 语言）',
        capability: 'audio',
        mode: 'sync',
        pricing: { price: 0.4, unit: '万字符' },
      },
    ],
  },
  {
    key: 'anthropic',
    label: 'Anthropic Claude',
    protocol: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    docsUrl: 'https://docs.anthropic.com/',
    description: 'Claude 系列，长文本剧本创作与结构化分镜效果好。',
    credentialFields: [{ key: 'apiKey', label: 'API Key' }],
    defaultModels: [
      { id: 'claude-sonnet-4-5', label: 'Claude Sonnet 4.5（文本）', capability: 'text', mode: 'sync' },
      { id: 'claude-haiku-4-5', label: 'Claude Haiku 4.5（快速文本）', capability: 'text', mode: 'sync' },
    ],
  },
  {
    key: 'gemini',
    label: 'Google Gemini',
    protocol: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com',
    docsUrl: 'https://ai.google.dev/gemini-api/docs',
    description: 'Gemini 文本/多模态、Gemini Image 生图、Veo 视频（异步）。',
    credentialFields: [{ key: 'apiKey', label: 'API Key' }],
    defaultModels: [
      { id: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro（文本）', capability: 'text', mode: 'sync' },
      {
        id: 'gemini-2.5-flash-image',
        label: 'Gemini 2.5 Flash Image（图片）',
        capability: 'image',
        mode: 'sync',
        supportsReferenceImage: true,
      },
      {
        id: 'veo-3.0-generate-preview',
        label: 'Veo 3（视频）',
        capability: 'video',
        mode: 'async',
        durations: [8],
        supportsFirstFrame: true,
      },
    ],
  },
  {
    key: 'runninghub',
    label: 'RunningHub（全模态聚合 API）',
    protocol: 'openai',
    baseUrl: 'https://api.runninghub.cn',
    docsUrl: 'https://www.runninghub.cn/call-api',
    description:
      '一个接口直连 400+ 模型：视频（Seedance / Kling / 万相）、图像（Seedream / qwen-image）、音频、3D，还托管 ComfyUI 工作流。OpenAI 兼容协议，按需计费。',
    credentialFields: [{ key: 'apiKey', label: 'API Key', hint: 'RunningHub 控制台 → 获取密钥' }],
    defaultModels: [
      {
        id: 'seedance-2.5/multimodal-video',
        label: 'Seedance 2.5（视频）',
        capability: 'video',
        mode: 'async',
        durations: [5, 10],
        supportsFirstFrame: true,
        supportsLastFrame: true,
        pricing: { price: 0.07, unit: '千 tokens' },
      },
      {
        id: 'seedream-v5-pro',
        label: 'Seedream v5 Pro（图片）',
        capability: 'image',
        mode: 'sync',
        supportsReferenceImage: true,
        pricing: { price: 0.3, unit: '张' },
      },
      {
        id: 'MiniMax-H3',
        label: 'MiniMax H3（视频）',
        capability: 'video',
        mode: 'async',
        durations: [6, 10],
        pricing: { price: 0.5, unit: '秒' },
      },
      {
        id: 'wan-3.0',
        label: '万相 3.0（视频）',
        capability: 'video',
        mode: 'async',
        durations: [5, 10],
        pricing: { price: 0.3, unit: '秒' },
      },
      {
        id: 'qwen3.7-max',
        label: 'qwen3.7-max（文本）',
        capability: 'text',
        mode: 'sync',
      },
      {
        id: 'seed-audio',
        label: 'Seed Audio（语音，20 语言）',
        capability: 'audio',
        mode: 'sync',
        pricing: { price: 0.3, unit: '万字符' },
      },
    ],
  },
];

export function findPreset(key: string): ProviderPreset | undefined {
  return PROVIDER_PRESETS.find((preset) => preset.key === key);
}
